apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-portfolio
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mon-portfolio
  template:
    metadata:
      labels:
        app: mon-portfolio
    spec:
      containers:
      - name: mon-portfolio
        image: cheikht/xesh-web:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      - name: prometheus-exporter
        image: nginx/nginx-prometheus-exporter:0.10.0
        args:
        - -nginx.scrape-uri=http://localhost:80/stub_status
        ports:
        - containerPort: 9113
